version: "3.8"

services:
  nextjs:
    container_name: skincare-competition
    build:
      context: .
    ports:
      - "3000:3000"
    restart: always
    environment:
      - NODE_ENV=development 
      - WATCHPACK_POLLING=true
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
